name: GitHub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "59 15 * * *"
  workflow_dispatch:
    
defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build-trixie-tag:
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim
    name: Build Trixie (Tag)
    steps:
      - uses: actions/checkout@v4

      - name: Update Lingmo repo
        run: |
          apt-get update -y && apt-get upgrade -y && apt-get install -y apt-transport-https ca-certificates
          echo "deb [trusted=yes] https://packages-lingmo.simplelinux.cn.eu.org/lingmo-archive/rolling/polaris polaris main contrib non-free" >> /etc/apt/sources.list.d/lingmo-rolling.list
          apt-get update

      - name: Update Apt and Install packages
        run: |
          apt-get update -y && apt-get upgrade -y
          apt-get install -y sudo equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ --no-install-recommends

      - name: Install PowerShell
        run: |
          curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/powershell_7.4.3-1.deb_amd64.deb -o powershell.deb
          apt-get install -y ./powershell.deb
          rm powershell.deb
      
      - name: Build Lingmo
        run: |
          git config --global http.sslVerify false
          git config --global advice.detachedHead false
          pwsh ./build.ps1
          
      - uses: actions/upload-artifact@v4
        with:
          name: Lingmo Artifacts hydrogen (Tag)
          path: BuildArtifacts
          compression-level: 9 # maximum compression

  build-trixie-git:
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim
    name: Build Trixie (Git)
    steps:
      - uses: actions/checkout@v4

      - name: Update Lingmo repo
        run: |
          apt-get update -y && apt-get upgrade -y && apt-get install -y apt-transport-https ca-certificates
          echo "deb [trusted=yes] https://packages-lingmo.simplelinux.cn.eu.org/lingmo-archive/rolling/polaris polaris main contrib non-free" >> /etc/apt/sources.list.d/lingmo-rolling.list
          apt-get update

      - name: Update Apt and Install packages
        run: |
          apt-get update -y && apt-get upgrade -y
          apt-get install -y sudo equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ --no-install-recommends

      - name: Install PowerShell
        run: |
          curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/powershell_7.4.3-1.deb_amd64.deb -o powershell.deb
          apt-get install -y ./powershell.deb
          rm powershell.deb
      
      - name: Build Lingmo
        run: |
          git config --global http.sslVerify false
          git config --global advice.detachedHead false
          pwsh ./build.ps1 1
          
      - uses: actions/upload-artifact@v4
        with:
          name: Lingmo Artifacts hydrogen (Git)
          path: BuildArtifacts
          compression-level: 9 # maximum compression


   
